version: '3.8'

services:
  backend:
    build:
      context: ./Comment & Notify Service/QLDA_PCCV
      dockerfile: Dockerfile
    ports:
      - "5003:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      # Chú ý: Đổi lại chuỗi kết nối cho đúng với DB của bạn trên VPS
      # - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=QLDA;User=sa;Password=YourStrong!Passw0rd;TrustServerCertificate=True;
    depends_on:
      - sqlserver
    restart: always
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always
    networks:
      - app-network

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "manhduy11@"
    ports:
      - "14333:1433"
    restart: always
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
