version: '3.8'

services:
  backend:
    build:
      context: ./Comment & Notify Service/QLDA_PCCV
      dockerfile: Dockerfile
    ports:
      - "5003:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultDb=Host=103.178.235.78;Port=5432;Database=QLDA_PCCV;Username=haiquan;Password=haiquan123456;
    restart: always
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
